services:
  cassandra:
    image: cassandra:5.0.5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: chat-memory-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator   # enables username/password
      CASSANDRA_AUTHORIZER: CassandraAuthorizer
    volumes:
      - ./cql-init:/docker-entrypoint-initdb.d
