spring:
  ai:
    openai:
      api-key:
    chat:
      memory:
        repository:
          cassandra:
            keyspace: spring
            initialize-schema: false

  cassandra:
      contactPoints: 127.0.0.1
      port: 9042
      localDatacenter: datacenter1
      username: cassandra
      password: cassandra
