spring:
  ai:
    openai:
      api-key:
    chat:
      memory:
        repository:
          jdbc:
            schema: classpath:/schema/schema-postgres.sql

  datasource:
    url: jdbc:h2:mem:chatdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true